# Generated by Django 4.1.2 on 2022-11-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rubric_subrubric_superrubric_rubric_super_rubric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superrubric',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Надрубрика', 'verbose_name_plural': 'Надрубрики'},
        ),
    ]
